Models/ErrorViewModel.cs
namespace EventAppCase.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Event.cs
namespace EventAppCase.Models
{
    public class Event
    {
        public int EventId { get; set; }
        public string? EventName { get; set; }
        public string? EventDetails { get; set; }
        public DateTime EventDate { get; set; }
        public string? EventLocation { get; set; }
    }
}

Models/EventContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace EventAppCase.Models
{
    public class EventContext: DbContext
    {
        public DbSet<Event> Events { get; set; }
        public DbSet<Guest> Guests { get; set; }
        public DbSet<SelectedGuests> SGuests { get; set; }

        public EventContext(DbContextOptions options) : base(options)
        {

        }


    }
}

Models/Guest.cs
using System.ComponentModel.DataAnnotations;

namespace EventAppCase.Models
{
    public class Guest
    {

        [Key] public int GuestId { get; set; }
        public string? GuestName { get; set; }
        public string? GuestSurname { get; set; }
        public string? GuestMail { get; set; }

        public string GuestAdSoyad
        {
            get
            {
                return this.GuestName + " " + GuestSurname;
            }
        }


    }
}

Models/SelectedGuests.cs
using System.ComponentModel.DataAnnotations;

namespace EventAppCase.Models
{
    public class SelectedGuests
    {
       [Key] public int Id { get; set; }
        public int GuestId { get; set; }

        public Guest Guest { get; set; } = null!; //joinleme için

        public int EventId { get; set; }

        public Event Event { get; set; } = null!; //joinleme için

        public DateTime SelectedDate { get; set; }
    }
}

Controllers/EventController.cs
using EventAppCase.Models;
using LinqToDB;
using Microsoft.AspNetCore.Mvc;


namespace EventAppCase.Controllers
{
    public class EventController : Controller
    {
        private readonly EventContext _context;

        public EventController(EventContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Apply()
        {
            return View();
        }




        public IActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateEvent(Event _event)
        {
            _context.Events.Add(_event);
            await _context.SaveChangesAsync();
            return RedirectToAction("EventList", "Event");

        }


        [HttpGet]
        public async Task<IActionResult> EventList()
        {
            var events = await _context.Events.ToListAsync();
            return View(events);
        }

        public async Task<IActionResult> EventDetail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var myDetail = await _context.Events.FindAsync(id);

            if (myDetail == null)
            {
                return NotFound();
            }

            return View(myDetail);

        }


    }
}

Controllers/GuestController.cs
using EventAppCase.Models;
using LinqToDB;
using Microsoft.AspNetCore.Mvc;

namespace EventAppCase.Controllers
{
    public class GuestController : Controller
    {
        private readonly EventContext _context;

        public GuestController(EventContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GuestList()
        {
            var guests = await _context.Guests.ToListAsync();
            return View(guests);
        }

        public IActionResult CreateGuest()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateGuest(Guest _guest)
        {
            _context.Guests.Add(_guest);
            await _context.SaveChangesAsync();
            return RedirectToAction("GuestList", "Guest");

        }
    }
}

Controllers/HomeController.cs
using EventAppCase.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EventAppCase.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return RedirectToAction("EventList", "Event");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SelectedGEController.cs
using EventAppCase.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace EventAppCase.Controllers
{
    public class SelectedGEController : Controller
    {
        private readonly EventContext _context;

        public SelectedGEController(EventContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var selectedGeValues = await _context.SGuests.Include(x=> x.Guest).Include(x=>x.Event).ToListAsync();
            return View(selectedGeValues);
        }

        public async Task<IActionResult> CreateGE()
        {
            ViewBag.Events = new SelectList(await _context.Events.ToListAsync(),"EventId","EventName");
            ViewBag.Guests= new SelectList(await _context.Guests.ToListAsync(), "GuestId", "GuestAdSoyad");

            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGE(SelectedGuests model)
        {
            model.SelectedDate = DateTime.Now;
           _context.SGuests.Add(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");

        }
    }
}

Views/Event/Apply.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Etkinlik Katılım Ekranı</h1>

Views/Event/CreateEvent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Event

<h1>Yeni Etkinlik Oluştur</h1>
<br />
<a href="/Event/EventList" class="btn btn-primary">Kayıtlı Etkinliklere Dön</a>
<br />
<form asp-controller="Event" asp-action="CreateEvent" method="post">
    <div class="mb-3">
        <label asp-for="EventDate" class="form-label">Etkinlik Tarihi:</label>
        <input asp-for="EventDate" type="date" class="form-label" />
    </div>
    <div class="mb-3">
        <label asp-for="EventName" class="form-label">Etkinlik Adı:</label>
        <input asp-for="EventName" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="EventLocation" class="form-label">Etkinlik Yeri:</label>
        <input asp-for="EventLocation" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="EventDetails" class="form-label">Etkinlik Detayı:</label>
        <input asp-for="EventDetails" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Etkinliği Kaydet</button>
</form>

Views/Event/EventDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Event


<h2>Seçili Etkinlik Detayı:</h2><br />
<a href="/Event/EventList" class="btn btn-primary">Geri Git</a>
<form asp-controller="Event" asp-action="CreateEvent" method="post">
    <div class="mb-3">
        
        <input asp-for="EventId" type="hidden"/>
    </div>
    <div class="mb-3">
        <label asp-for="EventDate" class="form-label">Etkinlik Tarihi:</label>
        <input asp-for="EventDate" disabled="true" type="date" class="form-label"  />
    </div>
    <div class="mb-3">
        <label asp-for="EventName" class="form-label">Etkinlik Adı:</label>
        <input asp-for="EventName" disabled="true" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="EventLocation" class="form-label">Etkinlik Yeri:</label>
        <input asp-for="EventLocation" disabled="true" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="EventDetails" class="form-label">Etkinlik Detayı:</label>
        <input asp-for="EventDetails" disabled="true" class="form-control" />
    </div>

        <div class="mb-3">
            <label asp-for="EventDetails" class="form-label">Etkinlik Detayı:</label>
            <input asp-for="EventDetails" disabled="true" class="form-control" />
        </div>



</form>

Views/Event/EventList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Event>

    <h3>Geçerli Etkinlikler:</h3>
    <br />
    <a href="/Event/CreateEvent" class="btn btn-primary">Yeni Etkinlik Ekle</a>

    <br />
    <table class="table">
        <thead>
            <tr>
                <th>Etkinlik Adı:</th>
                <th>Etkinlik Tarihi:</th>
                <th>Adres:</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var myEvent in Model)
            {
                <tr>
                    <td>@myEvent.EventName</td>
                    <td>@myEvent.EventDate</td>
                    <td>@myEvent.EventLocation</td>
                    <td>
                        <a asp-controller="Event" asp-action="EventDetail" asp-route-id="@myEvent.EventId" class="btn btn-sm btn-primary">Etkinlik Detayı</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

Views/Event/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@Model IEnumerable<Event>

<h3>Geçerli Etkinlikler:</h3>
<a href="Event/CreateEvent" class="btn btn-primary">Yeni Etkinlik Ekle</a>
<table class="table">
    <thead>
        <tr>
            <th>Etkinlik Adı:</th>
            <th>Etknlik Tarihi:</th>
            <th>Adres:</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var myEvent in Model)
        {
           <tr>
                    <td>@myEvent.EventName</td>
                    <td>@myEvent.EventDate</td>
                    <td>@myEvent.EventLocation</td>
                <td>
                    <a href="" class="btn btn-sm btn-primary">Etkinlik Detayı</a>
                </td>
           </tr>
        }
    </tbody>
</table>

Views/Guest/CreateGuest.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Guest

<h1>Yeni Etkinlik Oluştur</h1>
<br />
<a href="/Guest/GuestList" class="btn btn-primary">Katılımcı Listesine Dön</a>
<br />
<form asp-controller="Guest" asp-action="CreateGuest" method="post">
    <div class="mb-3">
        <label asp-for="GuestName" class="form-label">Adı:</label>
        <input asp-for="GuestName" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="GuestSurname" class="form-label">Soyadı:</label>
        <input asp-for="GuestSurname" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="GuestMail" class="form-label">E-Posta:</label>
        <input asp-for="GuestMail" class="form-control" />
    </div>
   
    <button type="submit" class="btn btn-primary">Katılımcıyı Kaydet</button>
</form>

Views/Guest/GuestList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Guest>

    <h3>Katılımcı Listesi:</h3>
    <br />
    <a href="/Guest/CreateGuest" class="btn btn-primary">Yeni Katılımcı Ekle</a>
    
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>Ad</th>
                <th>Soyad</th>
                <th>E-Posta</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var myGuest in Model)
            {
                <tr>
                    <td>@myGuest.GuestName</td>
                    <td>@myGuest.GuestSurname</td>
                    <td>@myGuest.GuestMail</td>
                   
                </tr>
            }
        </tbody>
    </table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Etkinlik Listesi</h1>
    <a href="#">Etkinlik Oluştur</a>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

   
</div>

Views/SelectedGE/CreateGE.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model SelectedGuests

<h1>Etkinliğe Kayıt Olma</h1>
<a href="/SelectedGE" class="btn btn-primary">Geri Dön</a>
<form asp-controller="SelectedGE" asp-action="CreateGE" method="post">
    <div class="mb-3">
        <label asp-for="EventId" class="form-label">Etkinlik</label>
        <select asp-for ="EventId" asp-items="ViewBag.Events" class="form-control"></select>
    </div>
    <div class="mb-3">
        <label asp-for="GuestId" class="form-label">Katılımcı</label>
        <select asp-for="GuestId" asp-items="ViewBag.Guests" class="form-control"></select>
        
    </div>
 

    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>

Views/SelectedGE/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<SelectedGuests>

<h2>Etkinliklere Katılanların Listesi</h2>
<a href="/Event/EventList" class="btn btn-primary">Geri Dön</a>
<a href="/SelectedGE/CreateGE" class="btn btn-primary">Katlımcıya Etkinlik Ata</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width:150px">No:</th>
            <th>Katılımcı Adı:</th>
            <th>Etkinlik Adı:</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <td>@Html.DisplayFor(modelItem => item.Guest.GuestAdSoyad)</td>
                <td>@Html.DisplayFor(modelItem => item.Event.EventName)</td>


            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventAppCase</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventAppCase.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventAppCase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            
                            <a href="/Event/EventList" class="nav-link text-dark">Etkinlikler</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Guest/GuestList" class="nav-link text-dark">Katılımcılar</a>
                        </li>
                        <li class="nav-item">
                            <a href="/SelectedGE" class="nav-link text-dark">Etkinliklere Katılanlar</a>
                        </li>
                    </ul>
                    <p class="nav navbar-text"></p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EventAppCase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>